nacos:
  config:
    server-addr: nacos:8848
    username: nacos
    password: nacos
    auto-refresh: true
  server-address: nacos
  port: 8848
  username: nacos
  password: nacos

dubbo:
  scan:
    base-packages: com.cupacm.oj.service
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
  protocol:
    name: dubbo
    port: -1
  service:
    version: 1.0.0


spring:
  application:
    name: cupoj_core


server:
  tomcat:
    threads:
      min-spare: 50
      max: 1500
  port: 8081