package com.cupacm.oj.dao;

import com.cupacm.oj.dao.ContestProblem;
import com.cupacm.oj.dao.ContestProblemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContestProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(ContestProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(ContestProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(ContestProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(ContestProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<ContestProblem> selectByExampleWithRowbounds(ContestProblemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<ContestProblem> selectByExample(ContestProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    ContestProblem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") ContestProblem record, @Param("example") ContestProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") ContestProblem record, @Param("example") ContestProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKeySelective(ContestProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKey(ContestProblem record);
}