package com.cupacm.oj.dao;

import java.util.Date;

public class ContestSet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_set.contestset_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer contestsetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_set.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_set.creator
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_set.create_time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_set.visible
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Boolean visible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_set.defunct
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String defunct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_set.description
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_set.contestset_id
     *
     * @return the value of contest_set.contestset_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getContestsetId() {
        return contestsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_set.contestset_id
     *
     * @param contestsetId the value for contest_set.contestset_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setContestsetId(Integer contestsetId) {
        this.contestsetId = contestsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_set.title
     *
     * @return the value of contest_set.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_set.title
     *
     * @param title the value for contest_set.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_set.creator
     *
     * @return the value of contest_set.creator
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_set.creator
     *
     * @param creator the value for contest_set.creator
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_set.create_time
     *
     * @return the value of contest_set.create_time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_set.create_time
     *
     * @param createTime the value for contest_set.create_time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_set.visible
     *
     * @return the value of contest_set.visible
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Boolean getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_set.visible
     *
     * @param visible the value for contest_set.visible
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_set.defunct
     *
     * @return the value of contest_set.defunct
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getDefunct() {
        return defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_set.defunct
     *
     * @param defunct the value for contest_set.defunct
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setDefunct(String defunct) {
        this.defunct = defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_set.description
     *
     * @return the value of contest_set.description
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_set.description
     *
     * @param description the value for contest_set.description
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }
}