package com.cupacm.oj.dao;

public class ContestAssistant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_assistant.assistant_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer assistantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_assistant.contest_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer contestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_assistant.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_assistant.assistant_id
     *
     * @return the value of contest_assistant.assistant_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getAssistantId() {
        return assistantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_assistant.assistant_id
     *
     * @param assistantId the value for contest_assistant.assistant_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setAssistantId(Integer assistantId) {
        this.assistantId = assistantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_assistant.contest_id
     *
     * @return the value of contest_assistant.contest_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_assistant.contest_id
     *
     * @param contestId the value for contest_assistant.contest_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setContestId(Integer contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_assistant.user_id
     *
     * @return the value of contest_assistant.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_assistant.user_id
     *
     * @param userId the value for contest_assistant.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}