package com.cupacm.oj.dao;

import com.cupacm.oj.dao.Cprogram;
import com.cupacm.oj.dao.CprogramExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CprogramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprogram
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(CprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprogram
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(CprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprogram
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(Cprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprogram
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(Cprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprogram
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<Cprogram> selectByExampleWithRowbounds(CprogramExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprogram
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<Cprogram> selectByExample(CprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprogram
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Cprogram record, @Param("example") CprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprogram
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") Cprogram record, @Param("example") CprogramExample example);
}