package com.cupacm.oj.dao;

import java.util.Date;

public class Loginlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.password
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.ip
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.browser_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String browserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.browser_version
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String browserVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.os_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String osName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.os_version
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String osVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.user_id
     *
     * @return the value of loginlog.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.user_id
     *
     * @param userId the value for loginlog.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.password
     *
     * @return the value of loginlog.password
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.password
     *
     * @param password the value for loginlog.password
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.ip
     *
     * @return the value of loginlog.ip
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.ip
     *
     * @param ip the value for loginlog.ip
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.time
     *
     * @return the value of loginlog.time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.time
     *
     * @param time the value for loginlog.time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.browser_name
     *
     * @return the value of loginlog.browser_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getBrowserName() {
        return browserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.browser_name
     *
     * @param browserName the value for loginlog.browser_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setBrowserName(String browserName) {
        this.browserName = browserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.browser_version
     *
     * @return the value of loginlog.browser_version
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getBrowserVersion() {
        return browserVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.browser_version
     *
     * @param browserVersion the value for loginlog.browser_version
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setBrowserVersion(String browserVersion) {
        this.browserVersion = browserVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.os_name
     *
     * @return the value of loginlog.os_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getOsName() {
        return osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.os_name
     *
     * @param osName the value for loginlog.os_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setOsName(String osName) {
        this.osName = osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.os_version
     *
     * @return the value of loginlog.os_version
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.os_version
     *
     * @param osVersion the value for loginlog.os_version
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }
}