package com.cupacm.oj.dao;

import com.cupacm.oj.dao.Mention;
import com.cupacm.oj.dao.MentionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mention
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(MentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mention
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(MentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mention
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(Mention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mention
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(Mention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mention
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<Mention> selectByExampleWithRowbounds(MentionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mention
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<Mention> selectByExample(MentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mention
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Mention record, @Param("example") MentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mention
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") Mention record, @Param("example") MentionExample example);
}