package com.cupacm.oj.dao;

import com.cupacm.oj.dao.SourceCodeUser;
import com.cupacm.oj.dao.SourceCodeUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SourceCodeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(SourceCodeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(SourceCodeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByPrimaryKey(Integer solutionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(SourceCodeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(SourceCodeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<SourceCodeUser> selectByExampleWithBLOBsWithRowbounds(SourceCodeUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<SourceCodeUser> selectByExampleWithBLOBs(SourceCodeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<SourceCodeUser> selectByExampleWithRowbounds(SourceCodeUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<SourceCodeUser> selectByExample(SourceCodeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    SourceCodeUser selectByPrimaryKey(Integer solutionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") SourceCodeUser record, @Param("example") SourceCodeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") SourceCodeUser record, @Param("example") SourceCodeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") SourceCodeUser record, @Param("example") SourceCodeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKeySelective(SourceCodeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SourceCodeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_user
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKey(SourceCodeUser record);
}