package com.cupacm.oj.dao;

import com.cupacm.oj.dao.SpecialSubjectProblem;
import com.cupacm.oj.dao.SpecialSubjectProblemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SpecialSubjectProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(SpecialSubjectProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(SpecialSubjectProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(SpecialSubjectProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(SpecialSubjectProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<SpecialSubjectProblem> selectByExampleWithRowbounds(SpecialSubjectProblemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<SpecialSubjectProblem> selectByExample(SpecialSubjectProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") SpecialSubjectProblem record, @Param("example") SpecialSubjectProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_subject_problem
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") SpecialSubjectProblem record, @Param("example") SpecialSubjectProblemExample example);
}