package com.cupacm.oj.dao;

public class SpecialSubjectProblem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_problem.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_problem.topic_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_problem.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_problem.oj_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String ojName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject_problem.num
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_problem.problem_id
     *
     * @return the value of special_subject_problem.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_problem.problem_id
     *
     * @param problemId the value for special_subject_problem.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_problem.topic_id
     *
     * @return the value of special_subject_problem.topic_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_problem.topic_id
     *
     * @param topicId the value for special_subject_problem.topic_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_problem.title
     *
     * @return the value of special_subject_problem.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_problem.title
     *
     * @param title the value for special_subject_problem.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_problem.oj_name
     *
     * @return the value of special_subject_problem.oj_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getOjName() {
        return ojName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_problem.oj_name
     *
     * @param ojName the value for special_subject_problem.oj_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setOjName(String ojName) {
        this.ojName = ojName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject_problem.num
     *
     * @return the value of special_subject_problem.num
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject_problem.num
     *
     * @param num the value for special_subject_problem.num
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}