package com.cupacm.oj.dao;

public class SpecialSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject.topic_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject.defunct
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String defunct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject.private
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Byte Private;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject.vjudge
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Byte vjudge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject.langmask
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer langmask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject.password
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_subject.description
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject.topic_id
     *
     * @return the value of special_subject.topic_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject.topic_id
     *
     * @param topicId the value for special_subject.topic_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject.title
     *
     * @return the value of special_subject.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject.title
     *
     * @param title the value for special_subject.title
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject.defunct
     *
     * @return the value of special_subject.defunct
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getDefunct() {
        return defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject.defunct
     *
     * @param defunct the value for special_subject.defunct
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setDefunct(String defunct) {
        this.defunct = defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject.private
     *
     * @return the value of special_subject.private
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Byte getPrivate() {
        return Private;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject.private
     *
     * @param Private the value for special_subject.private
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setPrivate(Byte Private) {
        this.Private = Private;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject.vjudge
     *
     * @return the value of special_subject.vjudge
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Byte getVjudge() {
        return vjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject.vjudge
     *
     * @param vjudge the value for special_subject.vjudge
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setVjudge(Byte vjudge) {
        this.vjudge = vjudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject.langmask
     *
     * @return the value of special_subject.langmask
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getLangmask() {
        return langmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject.langmask
     *
     * @param langmask the value for special_subject.langmask
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setLangmask(Integer langmask) {
        this.langmask = langmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject.password
     *
     * @return the value of special_subject.password
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject.password
     *
     * @param password the value for special_subject.password
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_subject.description
     *
     * @return the value of special_subject.description
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_subject.description
     *
     * @param description the value for special_subject.description
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }
}