package com.cupacm.oj.dao;

import com.cupacm.oj.dao.TopicAssistant;
import com.cupacm.oj.dao.TopicAssistantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TopicAssistantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(TopicAssistantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(TopicAssistantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByPrimaryKey(Integer topicAssistantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(TopicAssistant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(TopicAssistant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<TopicAssistant> selectByExampleWithRowbounds(TopicAssistantExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<TopicAssistant> selectByExample(TopicAssistantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    TopicAssistant selectByPrimaryKey(Integer topicAssistantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") TopicAssistant record, @Param("example") TopicAssistantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") TopicAssistant record, @Param("example") TopicAssistantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKeySelective(TopicAssistant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_assistant
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKey(TopicAssistant record);
}