package com.cupacm.oj.dao;

import java.util.Date;

public class Tutorial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.tutorial_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer tutorialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.in_date
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Date inDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.solution_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer solutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.source
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.like
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer like;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.dislike
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer dislike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tutorial.content
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.tutorial_id
     *
     * @return the value of tutorial.tutorial_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getTutorialId() {
        return tutorialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.tutorial_id
     *
     * @param tutorialId the value for tutorial.tutorial_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setTutorialId(Integer tutorialId) {
        this.tutorialId = tutorialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.problem_id
     *
     * @return the value of tutorial.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.problem_id
     *
     * @param problemId the value for tutorial.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.in_date
     *
     * @return the value of tutorial.in_date
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.in_date
     *
     * @param inDate the value for tutorial.in_date
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.user_id
     *
     * @return the value of tutorial.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.user_id
     *
     * @param userId the value for tutorial.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.solution_id
     *
     * @return the value of tutorial.solution_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.solution_id
     *
     * @param solutionId the value for tutorial.solution_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setSolutionId(Integer solutionId) {
        this.solutionId = solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.source
     *
     * @return the value of tutorial.source
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.source
     *
     * @param source the value for tutorial.source
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.like
     *
     * @return the value of tutorial.like
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.like
     *
     * @param like the value for tutorial.like
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setLike(Integer like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.dislike
     *
     * @return the value of tutorial.dislike
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getDislike() {
        return dislike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.dislike
     *
     * @param dislike the value for tutorial.dislike
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setDislike(Integer dislike) {
        this.dislike = dislike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tutorial.content
     *
     * @return the value of tutorial.content
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tutorial.content
     *
     * @param content the value for tutorial.content
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }
}