package com.cupacm.oj.dao;

import com.cupacm.oj.dao.Tutorial;
import com.cupacm.oj.dao.TutorialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TutorialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(TutorialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(TutorialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByPrimaryKey(Integer tutorialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(Tutorial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(Tutorial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<Tutorial> selectByExampleWithBLOBsWithRowbounds(TutorialExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<Tutorial> selectByExampleWithBLOBs(TutorialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<Tutorial> selectByExampleWithRowbounds(TutorialExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<Tutorial> selectByExample(TutorialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    Tutorial selectByPrimaryKey(Integer tutorialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tutorial record, @Param("example") TutorialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Tutorial record, @Param("example") TutorialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") Tutorial record, @Param("example") TutorialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKeySelective(Tutorial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Tutorial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tutorial
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByPrimaryKey(Tutorial record);
}