package com.cupacm.oj.dao;

import com.cupacm.oj.dao.UsersAccount;
import com.cupacm.oj.dao.UsersAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UsersAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_account
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(UsersAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_account
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(UsersAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_account
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(UsersAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_account
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(UsersAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_account
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<UsersAccount> selectByExampleWithRowbounds(UsersAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_account
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<UsersAccount> selectByExample(UsersAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_account
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") UsersAccount record, @Param("example") UsersAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_account
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") UsersAccount record, @Param("example") UsersAccountExample example);
}