package com.cupacm.oj.dao;

import com.cupacm.oj.dao.VjudgeSourceCode;
import com.cupacm.oj.dao.VjudgeSourceCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VjudgeSourceCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    long countByExample(VjudgeSourceCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int deleteByExample(VjudgeSourceCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insert(VjudgeSourceCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int insertSelective(VjudgeSourceCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<VjudgeSourceCode> selectByExampleWithBLOBsWithRowbounds(VjudgeSourceCodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<VjudgeSourceCode> selectByExampleWithBLOBs(VjudgeSourceCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<VjudgeSourceCode> selectByExampleWithRowbounds(VjudgeSourceCodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    List<VjudgeSourceCode> selectByExample(VjudgeSourceCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") VjudgeSourceCode record, @Param("example") VjudgeSourceCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") VjudgeSourceCode record, @Param("example") VjudgeSourceCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source_code
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    int updateByExample(@Param("record") VjudgeSourceCode record, @Param("example") VjudgeSourceCodeExample example);
}