package com.cupacm.oj.dao;

import java.util.Date;

public class VjudgeSolution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.solution_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer solutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.memory
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer memory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.in_date
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Date inDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.result
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Short result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.language
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.ip
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.contest_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer contestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.num
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Byte num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.code_length
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Integer codeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.oj_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String ojName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.judger
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String judger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.ustatus
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Boolean ustatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.share
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private Boolean share;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_solution.runner_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    private String runnerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.solution_id
     *
     * @return the value of vjudge_solution.solution_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.solution_id
     *
     * @param solutionId the value for vjudge_solution.solution_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setSolutionId(Integer solutionId) {
        this.solutionId = solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.problem_id
     *
     * @return the value of vjudge_solution.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.problem_id
     *
     * @param problemId the value for vjudge_solution.problem_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.user_id
     *
     * @return the value of vjudge_solution.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.user_id
     *
     * @param userId the value for vjudge_solution.user_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.time
     *
     * @return the value of vjudge_solution.time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.time
     *
     * @param time the value for vjudge_solution.time
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.memory
     *
     * @return the value of vjudge_solution.memory
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getMemory() {
        return memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.memory
     *
     * @param memory the value for vjudge_solution.memory
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setMemory(Integer memory) {
        this.memory = memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.in_date
     *
     * @return the value of vjudge_solution.in_date
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.in_date
     *
     * @param inDate the value for vjudge_solution.in_date
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.result
     *
     * @return the value of vjudge_solution.result
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Short getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.result
     *
     * @param result the value for vjudge_solution.result
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setResult(Short result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.language
     *
     * @return the value of vjudge_solution.language
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.language
     *
     * @param language the value for vjudge_solution.language
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.ip
     *
     * @return the value of vjudge_solution.ip
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.ip
     *
     * @param ip the value for vjudge_solution.ip
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.contest_id
     *
     * @return the value of vjudge_solution.contest_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.contest_id
     *
     * @param contestId the value for vjudge_solution.contest_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setContestId(Integer contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.num
     *
     * @return the value of vjudge_solution.num
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Byte getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.num
     *
     * @param num the value for vjudge_solution.num
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setNum(Byte num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.code_length
     *
     * @return the value of vjudge_solution.code_length
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Integer getCodeLength() {
        return codeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.code_length
     *
     * @param codeLength the value for vjudge_solution.code_length
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setCodeLength(Integer codeLength) {
        this.codeLength = codeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.oj_name
     *
     * @return the value of vjudge_solution.oj_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getOjName() {
        return ojName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.oj_name
     *
     * @param ojName the value for vjudge_solution.oj_name
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setOjName(String ojName) {
        this.ojName = ojName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.judger
     *
     * @return the value of vjudge_solution.judger
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getJudger() {
        return judger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.judger
     *
     * @param judger the value for vjudge_solution.judger
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setJudger(String judger) {
        this.judger = judger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.ustatus
     *
     * @return the value of vjudge_solution.ustatus
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Boolean getUstatus() {
        return ustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.ustatus
     *
     * @param ustatus the value for vjudge_solution.ustatus
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setUstatus(Boolean ustatus) {
        this.ustatus = ustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.share
     *
     * @return the value of vjudge_solution.share
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public Boolean getShare() {
        return share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.share
     *
     * @param share the value for vjudge_solution.share
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setShare(Boolean share) {
        this.share = share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_solution.runner_id
     *
     * @return the value of vjudge_solution.runner_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public String getRunnerId() {
        return runnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_solution.runner_id
     *
     * @param runnerId the value for vjudge_solution.runner_id
     *
     * @mbg.generated Sun Nov 08 15:06:46 CST 2020
     */
    public void setRunnerId(String runnerId) {
        this.runnerId = runnerId;
    }
}