package com.cupacm.oj.dao;

public class AcmMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acm_member.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acm_member.level
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Byte level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acm_member.user_id
     *
     * @return the value of acm_member.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acm_member.user_id
     *
     * @param userId the value for acm_member.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acm_member.level
     *
     * @return the value of acm_member.level
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acm_member.level
     *
     * @param level the value for acm_member.level
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setLevel(Byte level) {
        this.level = level;
    }
}