package com.cupacm.oj.dao;

import java.util.Date;

public class ArticleContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_content.comment_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_content.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_content.create_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_content.edit_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Date editTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_content.article_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_content.content
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_content.comment_id
     *
     * @return the value of article_content.comment_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_content.comment_id
     *
     * @param commentId the value for article_content.comment_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_content.user_id
     *
     * @return the value of article_content.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_content.user_id
     *
     * @param userId the value for article_content.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_content.create_time
     *
     * @return the value of article_content.create_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_content.create_time
     *
     * @param createTime the value for article_content.create_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_content.edit_time
     *
     * @return the value of article_content.edit_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_content.edit_time
     *
     * @param editTime the value for article_content.edit_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_content.article_id
     *
     * @return the value of article_content.article_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_content.article_id
     *
     * @param articleId the value for article_content.article_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_content.content
     *
     * @return the value of article_content.content
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_content.content
     *
     * @param content the value for article_content.content
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }
}