package com.cupacm.oj.dao;

public class ContestCheat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_cheat.solution_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer solutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_cheat.contest_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer contestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_cheat.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_cheat.num
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_cheat.checked
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Boolean checked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_cheat.solution_id
     *
     * @return the value of contest_cheat.solution_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_cheat.solution_id
     *
     * @param solutionId the value for contest_cheat.solution_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setSolutionId(Integer solutionId) {
        this.solutionId = solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_cheat.contest_id
     *
     * @return the value of contest_cheat.contest_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_cheat.contest_id
     *
     * @param contestId the value for contest_cheat.contest_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setContestId(Integer contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_cheat.user_id
     *
     * @return the value of contest_cheat.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_cheat.user_id
     *
     * @param userId the value for contest_cheat.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_cheat.num
     *
     * @return the value of contest_cheat.num
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_cheat.num
     *
     * @param num the value for contest_cheat.num
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_cheat.checked
     *
     * @return the value of contest_cheat.checked
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_cheat.checked
     *
     * @param checked the value for contest_cheat.checked
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }
}