package com.cupacm.oj.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public ContestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContestIdIsNull() {
            addCriterion("contest_id is null");
            return (Criteria) this;
        }

        public Criteria andContestIdIsNotNull() {
            addCriterion("contest_id is not null");
            return (Criteria) this;
        }

        public Criteria andContestIdEqualTo(Integer value) {
            addCriterion("contest_id =", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdNotEqualTo(Integer value) {
            addCriterion("contest_id <>", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdGreaterThan(Integer value) {
            addCriterion("contest_id >", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("contest_id >=", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdLessThan(Integer value) {
            addCriterion("contest_id <", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdLessThanOrEqualTo(Integer value) {
            addCriterion("contest_id <=", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdIn(List<Integer> values) {
            addCriterion("contest_id in", values, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdNotIn(List<Integer> values) {
            addCriterion("contest_id not in", values, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdBetween(Integer value1, Integer value2) {
            addCriterion("contest_id between", value1, value2, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdNotBetween(Integer value1, Integer value2) {
            addCriterion("contest_id not between", value1, value2, "contestId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andDefunctIsNull() {
            addCriterion("defunct is null");
            return (Criteria) this;
        }

        public Criteria andDefunctIsNotNull() {
            addCriterion("defunct is not null");
            return (Criteria) this;
        }

        public Criteria andDefunctEqualTo(String value) {
            addCriterion("defunct =", value, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctNotEqualTo(String value) {
            addCriterion("defunct <>", value, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctGreaterThan(String value) {
            addCriterion("defunct >", value, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctGreaterThanOrEqualTo(String value) {
            addCriterion("defunct >=", value, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctLessThan(String value) {
            addCriterion("defunct <", value, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctLessThanOrEqualTo(String value) {
            addCriterion("defunct <=", value, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctLike(String value) {
            addCriterion("defunct like", value, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctNotLike(String value) {
            addCriterion("defunct not like", value, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctIn(List<String> values) {
            addCriterion("defunct in", values, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctNotIn(List<String> values) {
            addCriterion("defunct not in", values, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctBetween(String value1, String value2) {
            addCriterion("defunct between", value1, value2, "defunct");
            return (Criteria) this;
        }

        public Criteria andDefunctNotBetween(String value1, String value2) {
            addCriterion("defunct not between", value1, value2, "defunct");
            return (Criteria) this;
        }

        public Criteria andPrivateIsNull() {
            addCriterion("private is null");
            return (Criteria) this;
        }

        public Criteria andPrivateIsNotNull() {
            addCriterion("private is not null");
            return (Criteria) this;
        }

        public Criteria andPrivateEqualTo(Byte value) {
            addCriterion("private =", value, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateNotEqualTo(Byte value) {
            addCriterion("private <>", value, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateGreaterThan(Byte value) {
            addCriterion("private >", value, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateGreaterThanOrEqualTo(Byte value) {
            addCriterion("private >=", value, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateLessThan(Byte value) {
            addCriterion("private <", value, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateLessThanOrEqualTo(Byte value) {
            addCriterion("private <=", value, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateIn(List<Byte> values) {
            addCriterion("private in", values, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateNotIn(List<Byte> values) {
            addCriterion("private not in", values, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateBetween(Byte value1, Byte value2) {
            addCriterion("private between", value1, value2, "Private");
            return (Criteria) this;
        }

        public Criteria andPrivateNotBetween(Byte value1, Byte value2) {
            addCriterion("private not between", value1, value2, "Private");
            return (Criteria) this;
        }

        public Criteria andVjudgeIsNull() {
            addCriterion("vjudge is null");
            return (Criteria) this;
        }

        public Criteria andVjudgeIsNotNull() {
            addCriterion("vjudge is not null");
            return (Criteria) this;
        }

        public Criteria andVjudgeEqualTo(Byte value) {
            addCriterion("vjudge =", value, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeNotEqualTo(Byte value) {
            addCriterion("vjudge <>", value, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeGreaterThan(Byte value) {
            addCriterion("vjudge >", value, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeGreaterThanOrEqualTo(Byte value) {
            addCriterion("vjudge >=", value, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeLessThan(Byte value) {
            addCriterion("vjudge <", value, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeLessThanOrEqualTo(Byte value) {
            addCriterion("vjudge <=", value, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeIn(List<Byte> values) {
            addCriterion("vjudge in", values, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeNotIn(List<Byte> values) {
            addCriterion("vjudge not in", values, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeBetween(Byte value1, Byte value2) {
            addCriterion("vjudge between", value1, value2, "vjudge");
            return (Criteria) this;
        }

        public Criteria andVjudgeNotBetween(Byte value1, Byte value2) {
            addCriterion("vjudge not between", value1, value2, "vjudge");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleIsNull() {
            addCriterion("cmod_visible is null");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleIsNotNull() {
            addCriterion("cmod_visible is not null");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleEqualTo(Byte value) {
            addCriterion("cmod_visible =", value, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleNotEqualTo(Byte value) {
            addCriterion("cmod_visible <>", value, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleGreaterThan(Byte value) {
            addCriterion("cmod_visible >", value, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleGreaterThanOrEqualTo(Byte value) {
            addCriterion("cmod_visible >=", value, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleLessThan(Byte value) {
            addCriterion("cmod_visible <", value, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleLessThanOrEqualTo(Byte value) {
            addCriterion("cmod_visible <=", value, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleIn(List<Byte> values) {
            addCriterion("cmod_visible in", values, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleNotIn(List<Byte> values) {
            addCriterion("cmod_visible not in", values, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleBetween(Byte value1, Byte value2) {
            addCriterion("cmod_visible between", value1, value2, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andCmodVisibleNotBetween(Byte value1, Byte value2) {
            addCriterion("cmod_visible not between", value1, value2, "cmodVisible");
            return (Criteria) this;
        }

        public Criteria andHomeworkIsNull() {
            addCriterion("homework is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkIsNotNull() {
            addCriterion("homework is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkEqualTo(Byte value) {
            addCriterion("homework =", value, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkNotEqualTo(Byte value) {
            addCriterion("homework <>", value, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkGreaterThan(Byte value) {
            addCriterion("homework >", value, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkGreaterThanOrEqualTo(Byte value) {
            addCriterion("homework >=", value, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkLessThan(Byte value) {
            addCriterion("homework <", value, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkLessThanOrEqualTo(Byte value) {
            addCriterion("homework <=", value, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkIn(List<Byte> values) {
            addCriterion("homework in", values, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkNotIn(List<Byte> values) {
            addCriterion("homework not in", values, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkBetween(Byte value1, Byte value2) {
            addCriterion("homework between", value1, value2, "homework");
            return (Criteria) this;
        }

        public Criteria andHomeworkNotBetween(Byte value1, Byte value2) {
            addCriterion("homework not between", value1, value2, "homework");
            return (Criteria) this;
        }

        public Criteria andLangmaskIsNull() {
            addCriterion("langmask is null");
            return (Criteria) this;
        }

        public Criteria andLangmaskIsNotNull() {
            addCriterion("langmask is not null");
            return (Criteria) this;
        }

        public Criteria andLangmaskEqualTo(Long value) {
            addCriterion("langmask =", value, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskNotEqualTo(Long value) {
            addCriterion("langmask <>", value, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskGreaterThan(Long value) {
            addCriterion("langmask >", value, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskGreaterThanOrEqualTo(Long value) {
            addCriterion("langmask >=", value, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskLessThan(Long value) {
            addCriterion("langmask <", value, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskLessThanOrEqualTo(Long value) {
            addCriterion("langmask <=", value, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskIn(List<Long> values) {
            addCriterion("langmask in", values, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskNotIn(List<Long> values) {
            addCriterion("langmask not in", values, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskBetween(Long value1, Long value2) {
            addCriterion("langmask between", value1, value2, "langmask");
            return (Criteria) this;
        }

        public Criteria andLangmaskNotBetween(Long value1, Long value2) {
            addCriterion("langmask not between", value1, value2, "langmask");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andIpPolicyIsNull() {
            addCriterion("ip_policy is null");
            return (Criteria) this;
        }

        public Criteria andIpPolicyIsNotNull() {
            addCriterion("ip_policy is not null");
            return (Criteria) this;
        }

        public Criteria andIpPolicyEqualTo(String value) {
            addCriterion("ip_policy =", value, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyNotEqualTo(String value) {
            addCriterion("ip_policy <>", value, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyGreaterThan(String value) {
            addCriterion("ip_policy >", value, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyGreaterThanOrEqualTo(String value) {
            addCriterion("ip_policy >=", value, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyLessThan(String value) {
            addCriterion("ip_policy <", value, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyLessThanOrEqualTo(String value) {
            addCriterion("ip_policy <=", value, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyLike(String value) {
            addCriterion("ip_policy like", value, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyNotLike(String value) {
            addCriterion("ip_policy not like", value, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyIn(List<String> values) {
            addCriterion("ip_policy in", values, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyNotIn(List<String> values) {
            addCriterion("ip_policy not in", values, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyBetween(String value1, String value2) {
            addCriterion("ip_policy between", value1, value2, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andIpPolicyNotBetween(String value1, String value2) {
            addCriterion("ip_policy not between", value1, value2, "ipPolicy");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameIsNull() {
            addCriterion("limit_hostname is null");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameIsNotNull() {
            addCriterion("limit_hostname is not null");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameEqualTo(String value) {
            addCriterion("limit_hostname =", value, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameNotEqualTo(String value) {
            addCriterion("limit_hostname <>", value, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameGreaterThan(String value) {
            addCriterion("limit_hostname >", value, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameGreaterThanOrEqualTo(String value) {
            addCriterion("limit_hostname >=", value, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameLessThan(String value) {
            addCriterion("limit_hostname <", value, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameLessThanOrEqualTo(String value) {
            addCriterion("limit_hostname <=", value, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameLike(String value) {
            addCriterion("limit_hostname like", value, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameNotLike(String value) {
            addCriterion("limit_hostname not like", value, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameIn(List<String> values) {
            addCriterion("limit_hostname in", values, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameNotIn(List<String> values) {
            addCriterion("limit_hostname not in", values, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameBetween(String value1, String value2) {
            addCriterion("limit_hostname between", value1, value2, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andLimitHostnameNotBetween(String value1, String value2) {
            addCriterion("limit_hostname not between", value1, value2, "limitHostname");
            return (Criteria) this;
        }

        public Criteria andMakerIsNull() {
            addCriterion("maker is null");
            return (Criteria) this;
        }

        public Criteria andMakerIsNotNull() {
            addCriterion("maker is not null");
            return (Criteria) this;
        }

        public Criteria andMakerEqualTo(String value) {
            addCriterion("maker =", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotEqualTo(String value) {
            addCriterion("maker <>", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerGreaterThan(String value) {
            addCriterion("maker >", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerGreaterThanOrEqualTo(String value) {
            addCriterion("maker >=", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLessThan(String value) {
            addCriterion("maker <", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLessThanOrEqualTo(String value) {
            addCriterion("maker <=", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLike(String value) {
            addCriterion("maker like", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotLike(String value) {
            addCriterion("maker not like", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerIn(List<String> values) {
            addCriterion("maker in", values, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotIn(List<String> values) {
            addCriterion("maker not in", values, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerBetween(String value1, String value2) {
            addCriterion("maker between", value1, value2, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotBetween(String value1, String value2) {
            addCriterion("maker not between", value1, value2, "maker");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistIsNull() {
            addCriterion("show_all_ranklist is null");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistIsNotNull() {
            addCriterion("show_all_ranklist is not null");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistEqualTo(Byte value) {
            addCriterion("show_all_ranklist =", value, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistNotEqualTo(Byte value) {
            addCriterion("show_all_ranklist <>", value, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistGreaterThan(Byte value) {
            addCriterion("show_all_ranklist >", value, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistGreaterThanOrEqualTo(Byte value) {
            addCriterion("show_all_ranklist >=", value, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistLessThan(Byte value) {
            addCriterion("show_all_ranklist <", value, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistLessThanOrEqualTo(Byte value) {
            addCriterion("show_all_ranklist <=", value, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistIn(List<Byte> values) {
            addCriterion("show_all_ranklist in", values, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistNotIn(List<Byte> values) {
            addCriterion("show_all_ranklist not in", values, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistBetween(Byte value1, Byte value2) {
            addCriterion("show_all_ranklist between", value1, value2, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowAllRanklistNotBetween(Byte value1, Byte value2) {
            addCriterion("show_all_ranklist not between", value1, value2, "showAllRanklist");
            return (Criteria) this;
        }

        public Criteria andShowSimIsNull() {
            addCriterion("show_sim is null");
            return (Criteria) this;
        }

        public Criteria andShowSimIsNotNull() {
            addCriterion("show_sim is not null");
            return (Criteria) this;
        }

        public Criteria andShowSimEqualTo(Byte value) {
            addCriterion("show_sim =", value, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimNotEqualTo(Byte value) {
            addCriterion("show_sim <>", value, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimGreaterThan(Byte value) {
            addCriterion("show_sim >", value, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimGreaterThanOrEqualTo(Byte value) {
            addCriterion("show_sim >=", value, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimLessThan(Byte value) {
            addCriterion("show_sim <", value, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimLessThanOrEqualTo(Byte value) {
            addCriterion("show_sim <=", value, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimIn(List<Byte> values) {
            addCriterion("show_sim in", values, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimNotIn(List<Byte> values) {
            addCriterion("show_sim not in", values, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimBetween(Byte value1, Byte value2) {
            addCriterion("show_sim between", value1, value2, "showSim");
            return (Criteria) this;
        }

        public Criteria andShowSimNotBetween(Byte value1, Byte value2) {
            addCriterion("show_sim not between", value1, value2, "showSim");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contest
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 08 15:44:09 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contest
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}