package com.cupacm.oj.dao;

import java.util.Date;

public class ContestClarification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_clarification.discuss_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer discussId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_clarification.contest_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer contestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_clarification.time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contest_clarification.content
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_clarification.discuss_id
     *
     * @return the value of contest_clarification.discuss_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getDiscussId() {
        return discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_clarification.discuss_id
     *
     * @param discussId the value for contest_clarification.discuss_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setDiscussId(Integer discussId) {
        this.discussId = discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_clarification.contest_id
     *
     * @return the value of contest_clarification.contest_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_clarification.contest_id
     *
     * @param contestId the value for contest_clarification.contest_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setContestId(Integer contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_clarification.time
     *
     * @return the value of contest_clarification.time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_clarification.time
     *
     * @param time the value for contest_clarification.time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contest_clarification.content
     *
     * @return the value of contest_clarification.content
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contest_clarification.content
     *
     * @param content the value for contest_clarification.content
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }
}