package com.cupacm.oj.dao;

import com.cupacm.oj.dao.Contestregister;
import com.cupacm.oj.dao.ContestregisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContestregisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    long countByExample(ContestregisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByExample(ContestregisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insert(Contestregister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insertSelective(Contestregister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<Contestregister> selectByExampleWithRowbounds(ContestregisterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<Contestregister> selectByExample(ContestregisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    Contestregister selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") Contestregister record, @Param("example") ContestregisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExample(@Param("record") Contestregister record, @Param("example") ContestregisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKeySelective(Contestregister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contestregister
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKey(Contestregister record);
}