package com.cupacm.oj.dao;

import java.util.Date;

public class Invite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.invite_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer inviteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.invite_code
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.valid_date
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Date validDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.valid_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer validTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.invite_id
     *
     * @return the value of invite.invite_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getInviteId() {
        return inviteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.invite_id
     *
     * @param inviteId the value for invite.invite_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setInviteId(Integer inviteId) {
        this.inviteId = inviteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.user_id
     *
     * @return the value of invite.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.user_id
     *
     * @param userId the value for invite.user_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.invite_code
     *
     * @return the value of invite.invite_code
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.invite_code
     *
     * @param inviteCode the value for invite.invite_code
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.valid_date
     *
     * @return the value of invite.valid_date
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.valid_date
     *
     * @param validDate the value for invite.valid_date
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.valid_time
     *
     * @return the value of invite.valid_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.valid_time
     *
     * @param validTime the value for invite.valid_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setValidTime(Integer validTime) {
        this.validTime = validTime;
    }
}