package com.cupacm.oj.dao;

import com.cupacm.oj.dao.Prefile;
import com.cupacm.oj.dao.PrefileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PrefileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    long countByExample(PrefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByExample(PrefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insert(Prefile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insertSelective(Prefile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<Prefile> selectByExampleWithBLOBsWithRowbounds(PrefileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<Prefile> selectByExampleWithBLOBs(PrefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<Prefile> selectByExampleWithRowbounds(PrefileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<Prefile> selectByExample(PrefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") Prefile record, @Param("example") PrefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Prefile record, @Param("example") PrefileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefile
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExample(@Param("record") Prefile record, @Param("example") PrefileExample example);
}