package com.cupacm.oj.dao;

public class Prefile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefile.problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefile.prepend
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Byte prepend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefile.type
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefile.code
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefile.problem_id
     *
     * @return the value of prefile.problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefile.problem_id
     *
     * @param problemId the value for prefile.problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefile.prepend
     *
     * @return the value of prefile.prepend
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Byte getPrepend() {
        return prepend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefile.prepend
     *
     * @param prepend the value for prefile.prepend
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setPrepend(Byte prepend) {
        this.prepend = prepend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefile.type
     *
     * @return the value of prefile.type
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefile.type
     *
     * @param type the value for prefile.type
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefile.code
     *
     * @return the value of prefile.code
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefile.code
     *
     * @param code the value for prefile.code
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }
}