package com.cupacm.oj.dao;

import java.util.Date;

public class Switch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.key
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.value
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.comment
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.modify_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.createdAt
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.updatedAt
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.key
     *
     * @return the value of switch.key
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.key
     *
     * @param key the value for switch.key
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.value
     *
     * @return the value of switch.value
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.value
     *
     * @param value the value for switch.value
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.comment
     *
     * @return the value of switch.comment
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.comment
     *
     * @param comment the value for switch.comment
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.modify_time
     *
     * @return the value of switch.modify_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.modify_time
     *
     * @param modifyTime the value for switch.modify_time
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.createdAt
     *
     * @return the value of switch.createdAt
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.createdAt
     *
     * @param createdat the value for switch.createdAt
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.updatedAt
     *
     * @return the value of switch.updatedAt
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.updatedAt
     *
     * @param updatedat the value for switch.updatedAt
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}