package com.cupacm.oj.dao;

import com.cupacm.oj.dao.VjudgeRecord;
import com.cupacm.oj.dao.VjudgeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VjudgeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_record
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    long countByExample(VjudgeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_record
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByExample(VjudgeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_record
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insert(VjudgeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_record
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insertSelective(VjudgeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_record
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeRecord> selectByExampleWithRowbounds(VjudgeRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_record
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeRecord> selectByExample(VjudgeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_record
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") VjudgeRecord record, @Param("example") VjudgeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_record
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExample(@Param("record") VjudgeRecord record, @Param("example") VjudgeRecordExample example);
}