package com.cupacm.oj.dao;

import com.cupacm.oj.dao.VjudgeOriginalProblem;
import com.cupacm.oj.dao.VjudgeOriginalProblemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VjudgeOriginalProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    long countByExample(VjudgeOriginalProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByExample(VjudgeOriginalProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByPrimaryKey(String originalProblemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insert(VjudgeOriginalProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insertSelective(VjudgeOriginalProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeOriginalProblem> selectByExampleWithRowbounds(VjudgeOriginalProblemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeOriginalProblem> selectByExample(VjudgeOriginalProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    VjudgeOriginalProblem selectByPrimaryKey(String originalProblemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") VjudgeOriginalProblem record, @Param("example") VjudgeOriginalProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExample(@Param("record") VjudgeOriginalProblem record, @Param("example") VjudgeOriginalProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKeySelective(VjudgeOriginalProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_original_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKey(VjudgeOriginalProblem record);
}