package com.cupacm.oj.dao;

public class VjudgeCustomInput {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_custom_input.solution_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer solutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_custom_input.input_text
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String inputText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_custom_input.solution_id
     *
     * @return the value of vjudge_custom_input.solution_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_custom_input.solution_id
     *
     * @param solutionId the value for vjudge_custom_input.solution_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setSolutionId(Integer solutionId) {
        this.solutionId = solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_custom_input.input_text
     *
     * @return the value of vjudge_custom_input.input_text
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getInputText() {
        return inputText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_custom_input.input_text
     *
     * @param inputText the value for vjudge_custom_input.input_text
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setInputText(String inputText) {
        this.inputText = inputText;
    }
}