package com.cupacm.oj.dao;

import com.cupacm.oj.dao.VjudgeCustomInput;
import com.cupacm.oj.dao.VjudgeCustomInputExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VjudgeCustomInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    long countByExample(VjudgeCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByExample(VjudgeCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insert(VjudgeCustomInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insertSelective(VjudgeCustomInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeCustomInput> selectByExampleWithBLOBsWithRowbounds(VjudgeCustomInputExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeCustomInput> selectByExampleWithBLOBs(VjudgeCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeCustomInput> selectByExampleWithRowbounds(VjudgeCustomInputExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeCustomInput> selectByExample(VjudgeCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") VjudgeCustomInput record, @Param("example") VjudgeCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") VjudgeCustomInput record, @Param("example") VjudgeCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_custom_input
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExample(@Param("record") VjudgeCustomInput record, @Param("example") VjudgeCustomInputExample example);
}