package com.cupacm.oj.dao;

public class VjudgeSource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_source.source_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_source.name
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_source.source_id
     *
     * @return the value of vjudge_source.source_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_source.source_id
     *
     * @param sourceId the value for vjudge_source.source_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_source.name
     *
     * @return the value of vjudge_source.name
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_source.name
     *
     * @param name the value for vjudge_source.name
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}