package com.cupacm.oj.dao;

public class VjudgeOriginalProblem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_original_problem.original_problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String originalProblemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_original_problem.problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vjudge_original_problem.source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_original_problem.original_problem_id
     *
     * @return the value of vjudge_original_problem.original_problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getOriginalProblemId() {
        return originalProblemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_original_problem.original_problem_id
     *
     * @param originalProblemId the value for vjudge_original_problem.original_problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setOriginalProblemId(String originalProblemId) {
        this.originalProblemId = originalProblemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_original_problem.problem_id
     *
     * @return the value of vjudge_original_problem.problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_original_problem.problem_id
     *
     * @param problemId the value for vjudge_original_problem.problem_id
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vjudge_original_problem.source
     *
     * @return the value of vjudge_original_problem.source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vjudge_original_problem.source
     *
     * @param source the value for vjudge_original_problem.source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    public void setSource(String source) {
        this.source = source;
    }
}