package com.cupacm.oj.dao;

import com.cupacm.oj.dao.VjudgeProblem;
import com.cupacm.oj.dao.VjudgeProblemExample;
import com.cupacm.oj.dao.VjudgeProblemWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VjudgeProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    long countByExample(VjudgeProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByExample(VjudgeProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByPrimaryKey(Integer vjudgeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insert(VjudgeProblemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insertSelective(VjudgeProblemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeProblemWithBLOBs> selectByExampleWithBLOBsWithRowbounds(VjudgeProblemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeProblemWithBLOBs> selectByExampleWithBLOBs(VjudgeProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeProblem> selectByExampleWithRowbounds(VjudgeProblemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeProblem> selectByExample(VjudgeProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    VjudgeProblemWithBLOBs selectByPrimaryKey(Integer vjudgeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") VjudgeProblemWithBLOBs record, @Param("example") VjudgeProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") VjudgeProblemWithBLOBs record, @Param("example") VjudgeProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExample(@Param("record") VjudgeProblem record, @Param("example") VjudgeProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKeySelective(VjudgeProblemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(VjudgeProblemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_problem
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKey(VjudgeProblem record);
}