package com.cupacm.oj.dao;

import com.cupacm.oj.dao.VjudgeSource;
import com.cupacm.oj.dao.VjudgeSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VjudgeSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    long countByExample(VjudgeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByExample(VjudgeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int deleteByPrimaryKey(Integer sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insert(VjudgeSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int insertSelective(VjudgeSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeSource> selectByExampleWithRowbounds(VjudgeSourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    List<VjudgeSource> selectByExample(VjudgeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    VjudgeSource selectByPrimaryKey(Integer sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") VjudgeSource record, @Param("example") VjudgeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByExample(@Param("record") VjudgeSource record, @Param("example") VjudgeSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKeySelective(VjudgeSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vjudge_source
     *
     * @mbg.generated Sun Nov 08 15:44:09 CST 2020
     */
    int updateByPrimaryKey(VjudgeSource record);
}